
namespace Interfaz_proyecto_integrador
{
    partial class ModificarAutos
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ModificarAutos));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.bunifuGradientPanel2 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtIdSeguro = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel11 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtKilometraje = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel10 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtModelo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtClase = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtMatricula = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtMarca = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtGrupo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtFechaCompra = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuButton22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuGradientPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuGradientPanel2
            // 
            this.bunifuGradientPanel2.AccessibleRole = System.Windows.Forms.AccessibleRole.MenuBar;
            this.bunifuGradientPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel2.BackgroundImage")));
            this.bunifuGradientPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel2.BorderRadius = 1;
            this.bunifuGradientPanel2.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.bunifuGradientPanel2.GradientBottomLeft = System.Drawing.Color.SteelBlue;
            this.bunifuGradientPanel2.GradientBottomRight = System.Drawing.Color.RoyalBlue;
            this.bunifuGradientPanel2.GradientTopLeft = System.Drawing.Color.Teal;
            this.bunifuGradientPanel2.GradientTopRight = System.Drawing.Color.DarkCyan;
            this.bunifuGradientPanel2.Location = new System.Drawing.Point(0, 401);
            this.bunifuGradientPanel2.Name = "bunifuGradientPanel2";
            this.bunifuGradientPanel2.Quality = 10;
            this.bunifuGradientPanel2.Size = new System.Drawing.Size(1093, 54);
            this.bunifuGradientPanel2.TabIndex = 21;
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.AccessibleRole = System.Windows.Forms.AccessibleRole.MenuBar;
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.SteelBlue;
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.RoyalBlue;
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.Teal;
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.DarkCyan;
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(1093, 54);
            this.bunifuGradientPanel1.TabIndex = 20;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.AutoSize = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Britannic Bold", 24F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(396, 9);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(307, 42);
            this.bunifuLabel2.TabIndex = 2;
            this.bunifuLabel2.Text = "Modificar autos";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.DarkCyan;
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Atras";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.WaitCursor;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges1;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton21.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton21.ForeColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.WaitCursor;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.WaitCursor;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.RoyalBlue;
            this.bunifuButton21.IdleBorderRadius = 30;
            this.bunifuButton21.IdleBorderThickness = 2;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.DarkCyan;
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(355, 328);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 30;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 2;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.BorderRadius = 30;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 2;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.RoyalBlue;
            this.bunifuButton21.OnIdleState.BorderRadius = 30;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 2;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.DarkCyan;
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.BorderRadius = 30;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 2;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(182, 39);
            this.bunifuButton21.TabIndex = 22;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            this.bunifuButton21.UseWaitCursor = true;
            this.bunifuButton21.Click += new System.EventHandler(this.bunifuButton21_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 15F);
            this.bunifuLabel1.Location = new System.Drawing.Point(609, 260);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(116, 28);
            this.bunifuLabel1.TabIndex = 98;
            this.bunifuLabel1.Text = "ID del seguro";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtIdSeguro
            // 
            this.txtIdSeguro.AcceptsReturn = false;
            this.txtIdSeguro.AcceptsTab = false;
            this.txtIdSeguro.AnimationSpeed = 200;
            this.txtIdSeguro.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtIdSeguro.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtIdSeguro.AutoSizeHeight = true;
            this.txtIdSeguro.BackColor = System.Drawing.Color.Transparent;
            this.txtIdSeguro.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtIdSeguro.BackgroundImage")));
            this.txtIdSeguro.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtIdSeguro.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtIdSeguro.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtIdSeguro.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtIdSeguro.BorderRadius = 1;
            this.txtIdSeguro.BorderThickness = 1;
            this.txtIdSeguro.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtIdSeguro.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtIdSeguro.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtIdSeguro.DefaultText = "";
            this.txtIdSeguro.FillColor = System.Drawing.Color.White;
            this.txtIdSeguro.HideSelection = true;
            this.txtIdSeguro.IconLeft = null;
            this.txtIdSeguro.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtIdSeguro.IconPadding = 10;
            this.txtIdSeguro.IconRight = null;
            this.txtIdSeguro.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtIdSeguro.Lines = new string[0];
            this.txtIdSeguro.Location = new System.Drawing.Point(731, 250);
            this.txtIdSeguro.MaxLength = 32767;
            this.txtIdSeguro.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtIdSeguro.Modified = false;
            this.txtIdSeguro.Multiline = false;
            this.txtIdSeguro.Name = "txtIdSeguro";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtIdSeguro.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtIdSeguro.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtIdSeguro.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtIdSeguro.OnIdleState = stateProperties4;
            this.txtIdSeguro.Padding = new System.Windows.Forms.Padding(3);
            this.txtIdSeguro.PasswordChar = '\0';
            this.txtIdSeguro.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtIdSeguro.PlaceholderText = "CAMPO";
            this.txtIdSeguro.ReadOnly = false;
            this.txtIdSeguro.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtIdSeguro.SelectedText = "";
            this.txtIdSeguro.SelectionLength = 0;
            this.txtIdSeguro.SelectionStart = 0;
            this.txtIdSeguro.ShortcutsEnabled = true;
            this.txtIdSeguro.Size = new System.Drawing.Size(292, 39);
            this.txtIdSeguro.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtIdSeguro.TabIndex = 97;
            this.txtIdSeguro.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtIdSeguro.TextMarginBottom = 0;
            this.txtIdSeguro.TextMarginLeft = 3;
            this.txtIdSeguro.TextMarginTop = 1;
            this.txtIdSeguro.TextPlaceholder = "CAMPO";
            this.txtIdSeguro.UseSystemPasswordChar = false;
            this.txtIdSeguro.WordWrap = true;
            // 
            // bunifuLabel11
            // 
            this.bunifuLabel11.AllowParentOverrides = false;
            this.bunifuLabel11.AutoEllipsis = false;
            this.bunifuLabel11.CursorType = null;
            this.bunifuLabel11.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel11.Location = new System.Drawing.Point(604, 197);
            this.bunifuLabel11.Name = "bunifuLabel11";
            this.bunifuLabel11.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel11.Size = new System.Drawing.Size(121, 32);
            this.bunifuLabel11.TabIndex = 96;
            this.bunifuLabel11.Text = "Kilometraje";
            this.bunifuLabel11.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel11.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtKilometraje
            // 
            this.txtKilometraje.AcceptsReturn = false;
            this.txtKilometraje.AcceptsTab = false;
            this.txtKilometraje.AnimationSpeed = 200;
            this.txtKilometraje.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtKilometraje.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtKilometraje.AutoSizeHeight = true;
            this.txtKilometraje.BackColor = System.Drawing.Color.Transparent;
            this.txtKilometraje.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtKilometraje.BackgroundImage")));
            this.txtKilometraje.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtKilometraje.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtKilometraje.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtKilometraje.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtKilometraje.BorderRadius = 1;
            this.txtKilometraje.BorderThickness = 1;
            this.txtKilometraje.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtKilometraje.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtKilometraje.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtKilometraje.DefaultText = "";
            this.txtKilometraje.FillColor = System.Drawing.Color.White;
            this.txtKilometraje.HideSelection = true;
            this.txtKilometraje.IconLeft = null;
            this.txtKilometraje.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtKilometraje.IconPadding = 10;
            this.txtKilometraje.IconRight = null;
            this.txtKilometraje.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtKilometraje.Lines = new string[0];
            this.txtKilometraje.Location = new System.Drawing.Point(731, 190);
            this.txtKilometraje.MaxLength = 32767;
            this.txtKilometraje.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtKilometraje.Modified = false;
            this.txtKilometraje.Multiline = false;
            this.txtKilometraje.Name = "txtKilometraje";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtKilometraje.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtKilometraje.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtKilometraje.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtKilometraje.OnIdleState = stateProperties8;
            this.txtKilometraje.Padding = new System.Windows.Forms.Padding(3);
            this.txtKilometraje.PasswordChar = '\0';
            this.txtKilometraje.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtKilometraje.PlaceholderText = "CAMPO";
            this.txtKilometraje.ReadOnly = false;
            this.txtKilometraje.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtKilometraje.SelectedText = "";
            this.txtKilometraje.SelectionLength = 0;
            this.txtKilometraje.SelectionStart = 0;
            this.txtKilometraje.ShortcutsEnabled = true;
            this.txtKilometraje.Size = new System.Drawing.Size(292, 39);
            this.txtKilometraje.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtKilometraje.TabIndex = 95;
            this.txtKilometraje.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtKilometraje.TextMarginBottom = 0;
            this.txtKilometraje.TextMarginLeft = 3;
            this.txtKilometraje.TextMarginTop = 1;
            this.txtKilometraje.TextPlaceholder = "CAMPO";
            this.txtKilometraje.UseSystemPasswordChar = false;
            this.txtKilometraje.WordWrap = true;
            // 
            // bunifuLabel10
            // 
            this.bunifuLabel10.AllowParentOverrides = false;
            this.bunifuLabel10.AutoEllipsis = false;
            this.bunifuLabel10.CursorType = null;
            this.bunifuLabel10.Font = new System.Drawing.Font("Segoe UI", 20F);
            this.bunifuLabel10.Location = new System.Drawing.Point(146, 251);
            this.bunifuLabel10.Name = "bunifuLabel10";
            this.bunifuLabel10.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel10.Size = new System.Drawing.Size(93, 37);
            this.bunifuLabel10.TabIndex = 94;
            this.bunifuLabel10.Text = "Modelo";
            this.bunifuLabel10.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel10.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtModelo
            // 
            this.txtModelo.AcceptsReturn = false;
            this.txtModelo.AcceptsTab = false;
            this.txtModelo.AnimationSpeed = 200;
            this.txtModelo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtModelo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtModelo.AutoSizeHeight = true;
            this.txtModelo.BackColor = System.Drawing.Color.Transparent;
            this.txtModelo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtModelo.BackgroundImage")));
            this.txtModelo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtModelo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtModelo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtModelo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtModelo.BorderRadius = 1;
            this.txtModelo.BorderThickness = 1;
            this.txtModelo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtModelo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtModelo.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtModelo.DefaultText = "";
            this.txtModelo.FillColor = System.Drawing.Color.White;
            this.txtModelo.HideSelection = true;
            this.txtModelo.IconLeft = null;
            this.txtModelo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtModelo.IconPadding = 10;
            this.txtModelo.IconRight = null;
            this.txtModelo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtModelo.Lines = new string[0];
            this.txtModelo.Location = new System.Drawing.Point(245, 249);
            this.txtModelo.MaxLength = 32767;
            this.txtModelo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtModelo.Modified = false;
            this.txtModelo.Multiline = false;
            this.txtModelo.Name = "txtModelo";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtModelo.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtModelo.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtModelo.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtModelo.OnIdleState = stateProperties12;
            this.txtModelo.Padding = new System.Windows.Forms.Padding(3);
            this.txtModelo.PasswordChar = '\0';
            this.txtModelo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtModelo.PlaceholderText = "CAMPO";
            this.txtModelo.ReadOnly = false;
            this.txtModelo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtModelo.SelectedText = "";
            this.txtModelo.SelectionLength = 0;
            this.txtModelo.SelectionStart = 0;
            this.txtModelo.ShortcutsEnabled = true;
            this.txtModelo.Size = new System.Drawing.Size(292, 39);
            this.txtModelo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtModelo.TabIndex = 93;
            this.txtModelo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtModelo.TextMarginBottom = 0;
            this.txtModelo.TextMarginLeft = 3;
            this.txtModelo.TextMarginTop = 1;
            this.txtModelo.TextPlaceholder = "CAMPO";
            this.txtModelo.UseSystemPasswordChar = false;
            this.txtModelo.WordWrap = true;
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.CursorType = null;
            this.bunifuLabel9.Font = new System.Drawing.Font("Segoe UI", 20F);
            this.bunifuLabel9.Location = new System.Drawing.Point(176, 139);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(63, 37);
            this.bunifuLabel9.TabIndex = 92;
            this.bunifuLabel9.Text = "Clase";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtClase
            // 
            this.txtClase.AcceptsReturn = false;
            this.txtClase.AcceptsTab = false;
            this.txtClase.AnimationSpeed = 200;
            this.txtClase.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtClase.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtClase.AutoSizeHeight = true;
            this.txtClase.BackColor = System.Drawing.Color.Transparent;
            this.txtClase.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtClase.BackgroundImage")));
            this.txtClase.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtClase.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtClase.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtClase.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtClase.BorderRadius = 1;
            this.txtClase.BorderThickness = 1;
            this.txtClase.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtClase.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtClase.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtClase.DefaultText = "";
            this.txtClase.FillColor = System.Drawing.Color.White;
            this.txtClase.HideSelection = true;
            this.txtClase.IconLeft = null;
            this.txtClase.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtClase.IconPadding = 10;
            this.txtClase.IconRight = null;
            this.txtClase.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtClase.Lines = new string[0];
            this.txtClase.Location = new System.Drawing.Point(245, 137);
            this.txtClase.MaxLength = 32767;
            this.txtClase.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtClase.Modified = false;
            this.txtClase.Multiline = false;
            this.txtClase.Name = "txtClase";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtClase.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtClase.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtClase.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtClase.OnIdleState = stateProperties16;
            this.txtClase.Padding = new System.Windows.Forms.Padding(3);
            this.txtClase.PasswordChar = '\0';
            this.txtClase.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtClase.PlaceholderText = "CAMPO";
            this.txtClase.ReadOnly = false;
            this.txtClase.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtClase.SelectedText = "";
            this.txtClase.SelectionLength = 0;
            this.txtClase.SelectionStart = 0;
            this.txtClase.ShortcutsEnabled = true;
            this.txtClase.Size = new System.Drawing.Size(292, 39);
            this.txtClase.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtClase.TabIndex = 91;
            this.txtClase.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtClase.TextMarginBottom = 0;
            this.txtClase.TextMarginLeft = 3;
            this.txtClase.TextMarginTop = 1;
            this.txtClase.TextPlaceholder = "CAMPO";
            this.txtClase.UseSystemPasswordChar = false;
            this.txtClase.WordWrap = true;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Segoe UI", 20F);
            this.bunifuLabel8.Location = new System.Drawing.Point(128, 91);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(111, 37);
            this.bunifuLabel8.TabIndex = 90;
            this.bunifuLabel8.Text = "Matricula";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtMatricula
            // 
            this.txtMatricula.AcceptsReturn = false;
            this.txtMatricula.AcceptsTab = false;
            this.txtMatricula.AnimationSpeed = 200;
            this.txtMatricula.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMatricula.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMatricula.AutoSizeHeight = true;
            this.txtMatricula.BackColor = System.Drawing.Color.Transparent;
            this.txtMatricula.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMatricula.BackgroundImage")));
            this.txtMatricula.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMatricula.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMatricula.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMatricula.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMatricula.BorderRadius = 1;
            this.txtMatricula.BorderThickness = 1;
            this.txtMatricula.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMatricula.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMatricula.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtMatricula.DefaultText = "";
            this.txtMatricula.FillColor = System.Drawing.Color.White;
            this.txtMatricula.HideSelection = true;
            this.txtMatricula.IconLeft = null;
            this.txtMatricula.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMatricula.IconPadding = 10;
            this.txtMatricula.IconRight = null;
            this.txtMatricula.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMatricula.Lines = new string[0];
            this.txtMatricula.Location = new System.Drawing.Point(245, 89);
            this.txtMatricula.MaxLength = 32767;
            this.txtMatricula.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMatricula.Modified = false;
            this.txtMatricula.Multiline = false;
            this.txtMatricula.Name = "txtMatricula";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMatricula.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMatricula.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMatricula.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMatricula.OnIdleState = stateProperties20;
            this.txtMatricula.Padding = new System.Windows.Forms.Padding(3);
            this.txtMatricula.PasswordChar = '\0';
            this.txtMatricula.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMatricula.PlaceholderText = "CAMPO";
            this.txtMatricula.ReadOnly = false;
            this.txtMatricula.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMatricula.SelectedText = "";
            this.txtMatricula.SelectionLength = 0;
            this.txtMatricula.SelectionStart = 0;
            this.txtMatricula.ShortcutsEnabled = true;
            this.txtMatricula.Size = new System.Drawing.Size(292, 39);
            this.txtMatricula.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMatricula.TabIndex = 89;
            this.txtMatricula.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMatricula.TextMarginBottom = 0;
            this.txtMatricula.TextMarginLeft = 3;
            this.txtMatricula.TextMarginTop = 1;
            this.txtMatricula.TextPlaceholder = "CAMPO";
            this.txtMatricula.UseSystemPasswordChar = false;
            this.txtMatricula.WordWrap = true;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI", 20F);
            this.bunifuLabel7.Location = new System.Drawing.Point(650, 135);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(75, 37);
            this.bunifuLabel7.TabIndex = 88;
            this.bunifuLabel7.Text = "Grupo";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.Location = new System.Drawing.Point(54, 200);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(187, 32);
            this.bunifuLabel5.TabIndex = 87;
            this.bunifuLabel5.Text = "Fecha de Compra";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.Location = new System.Drawing.Point(654, 86);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(65, 32);
            this.bunifuLabel3.TabIndex = 86;
            this.bunifuLabel3.Text = "Marca";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtMarca
            // 
            this.txtMarca.AcceptsReturn = false;
            this.txtMarca.AcceptsTab = false;
            this.txtMarca.AnimationSpeed = 200;
            this.txtMarca.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMarca.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMarca.AutoSizeHeight = true;
            this.txtMarca.BackColor = System.Drawing.Color.Transparent;
            this.txtMarca.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMarca.BackgroundImage")));
            this.txtMarca.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMarca.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMarca.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMarca.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMarca.BorderRadius = 1;
            this.txtMarca.BorderThickness = 1;
            this.txtMarca.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMarca.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMarca.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtMarca.DefaultText = "";
            this.txtMarca.FillColor = System.Drawing.Color.White;
            this.txtMarca.HideSelection = true;
            this.txtMarca.IconLeft = null;
            this.txtMarca.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMarca.IconPadding = 10;
            this.txtMarca.IconRight = null;
            this.txtMarca.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMarca.Lines = new string[0];
            this.txtMarca.Location = new System.Drawing.Point(731, 79);
            this.txtMarca.MaxLength = 32767;
            this.txtMarca.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMarca.Modified = false;
            this.txtMarca.Multiline = false;
            this.txtMarca.Name = "txtMarca";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMarca.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMarca.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMarca.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMarca.OnIdleState = stateProperties24;
            this.txtMarca.Padding = new System.Windows.Forms.Padding(3);
            this.txtMarca.PasswordChar = '\0';
            this.txtMarca.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMarca.PlaceholderText = "Marca";
            this.txtMarca.ReadOnly = false;
            this.txtMarca.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMarca.SelectedText = "";
            this.txtMarca.SelectionLength = 0;
            this.txtMarca.SelectionStart = 0;
            this.txtMarca.ShortcutsEnabled = true;
            this.txtMarca.Size = new System.Drawing.Size(292, 39);
            this.txtMarca.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMarca.TabIndex = 85;
            this.txtMarca.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMarca.TextMarginBottom = 0;
            this.txtMarca.TextMarginLeft = 3;
            this.txtMarca.TextMarginTop = 1;
            this.txtMarca.TextPlaceholder = "Marca";
            this.txtMarca.UseSystemPasswordChar = false;
            this.txtMarca.WordWrap = true;
            // 
            // txtGrupo
            // 
            this.txtGrupo.AcceptsReturn = false;
            this.txtGrupo.AcceptsTab = false;
            this.txtGrupo.AnimationSpeed = 200;
            this.txtGrupo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtGrupo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtGrupo.AutoSizeHeight = true;
            this.txtGrupo.BackColor = System.Drawing.Color.Transparent;
            this.txtGrupo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtGrupo.BackgroundImage")));
            this.txtGrupo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtGrupo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtGrupo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtGrupo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtGrupo.BorderRadius = 1;
            this.txtGrupo.BorderThickness = 1;
            this.txtGrupo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtGrupo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGrupo.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtGrupo.DefaultText = "";
            this.txtGrupo.FillColor = System.Drawing.Color.White;
            this.txtGrupo.HideSelection = true;
            this.txtGrupo.IconLeft = null;
            this.txtGrupo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGrupo.IconPadding = 10;
            this.txtGrupo.IconRight = null;
            this.txtGrupo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGrupo.Lines = new string[0];
            this.txtGrupo.Location = new System.Drawing.Point(731, 135);
            this.txtGrupo.MaxLength = 32767;
            this.txtGrupo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtGrupo.Modified = false;
            this.txtGrupo.Multiline = false;
            this.txtGrupo.Name = "txtGrupo";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGrupo.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtGrupo.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGrupo.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtGrupo.OnIdleState = stateProperties28;
            this.txtGrupo.Padding = new System.Windows.Forms.Padding(3);
            this.txtGrupo.PasswordChar = '\0';
            this.txtGrupo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtGrupo.PlaceholderText = "CAMPO";
            this.txtGrupo.ReadOnly = false;
            this.txtGrupo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtGrupo.SelectedText = "";
            this.txtGrupo.SelectionLength = 0;
            this.txtGrupo.SelectionStart = 0;
            this.txtGrupo.ShortcutsEnabled = true;
            this.txtGrupo.Size = new System.Drawing.Size(292, 39);
            this.txtGrupo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtGrupo.TabIndex = 84;
            this.txtGrupo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtGrupo.TextMarginBottom = 0;
            this.txtGrupo.TextMarginLeft = 3;
            this.txtGrupo.TextMarginTop = 1;
            this.txtGrupo.TextPlaceholder = "CAMPO";
            this.txtGrupo.UseSystemPasswordChar = false;
            this.txtGrupo.WordWrap = true;
            // 
            // txtFechaCompra
            // 
            this.txtFechaCompra.AcceptsReturn = false;
            this.txtFechaCompra.AcceptsTab = false;
            this.txtFechaCompra.AnimationSpeed = 200;
            this.txtFechaCompra.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtFechaCompra.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtFechaCompra.AutoSizeHeight = true;
            this.txtFechaCompra.BackColor = System.Drawing.Color.Transparent;
            this.txtFechaCompra.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFechaCompra.BackgroundImage")));
            this.txtFechaCompra.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtFechaCompra.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtFechaCompra.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtFechaCompra.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtFechaCompra.BorderRadius = 1;
            this.txtFechaCompra.BorderThickness = 1;
            this.txtFechaCompra.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFechaCompra.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFechaCompra.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtFechaCompra.DefaultText = "";
            this.txtFechaCompra.FillColor = System.Drawing.Color.White;
            this.txtFechaCompra.HideSelection = true;
            this.txtFechaCompra.IconLeft = null;
            this.txtFechaCompra.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFechaCompra.IconPadding = 10;
            this.txtFechaCompra.IconRight = null;
            this.txtFechaCompra.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFechaCompra.Lines = new string[0];
            this.txtFechaCompra.Location = new System.Drawing.Point(245, 193);
            this.txtFechaCompra.MaxLength = 32767;
            this.txtFechaCompra.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFechaCompra.Modified = false;
            this.txtFechaCompra.Multiline = false;
            this.txtFechaCompra.Name = "txtFechaCompra";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFechaCompra.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtFechaCompra.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFechaCompra.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFechaCompra.OnIdleState = stateProperties32;
            this.txtFechaCompra.Padding = new System.Windows.Forms.Padding(3);
            this.txtFechaCompra.PasswordChar = '\0';
            this.txtFechaCompra.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtFechaCompra.PlaceholderText = "DD/MM/AAAA";
            this.txtFechaCompra.ReadOnly = false;
            this.txtFechaCompra.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFechaCompra.SelectedText = "";
            this.txtFechaCompra.SelectionLength = 0;
            this.txtFechaCompra.SelectionStart = 0;
            this.txtFechaCompra.ShortcutsEnabled = true;
            this.txtFechaCompra.Size = new System.Drawing.Size(292, 39);
            this.txtFechaCompra.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtFechaCompra.TabIndex = 83;
            this.txtFechaCompra.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtFechaCompra.TextMarginBottom = 0;
            this.txtFechaCompra.TextMarginLeft = 3;
            this.txtFechaCompra.TextMarginTop = 1;
            this.txtFechaCompra.TextPlaceholder = "DD/MM/AAAA";
            this.txtFechaCompra.UseSystemPasswordChar = false;
            this.txtFechaCompra.WordWrap = true;
            // 
            // bunifuButton22
            // 
            this.bunifuButton22.AllowAnimations = true;
            this.bunifuButton22.AllowMouseEffects = true;
            this.bunifuButton22.AllowToggling = false;
            this.bunifuButton22.AnimationSpeed = 200;
            this.bunifuButton22.AutoGenerateColors = false;
            this.bunifuButton22.AutoRoundBorders = false;
            this.bunifuButton22.AutoSizeLeftIcon = true;
            this.bunifuButton22.AutoSizeRightIcon = true;
            this.bunifuButton22.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.BackColor1 = System.Drawing.Color.DarkCyan;
            this.bunifuButton22.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton22.BackgroundImage")));
            this.bunifuButton22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.ButtonText = "Modificar";
            this.bunifuButton22.ButtonTextMarginLeft = 0;
            this.bunifuButton22.ColorContrastOnClick = 45;
            this.bunifuButton22.ColorContrastOnHover = 45;
            this.bunifuButton22.Cursor = System.Windows.Forms.Cursors.WaitCursor;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton22.CustomizableEdges = borderEdges2;
            this.bunifuButton22.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton22.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton22.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton22.ForeColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton22.IconLeftCursor = System.Windows.Forms.Cursors.WaitCursor;
            this.bunifuButton22.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton22.IconMarginLeft = 11;
            this.bunifuButton22.IconPadding = 10;
            this.bunifuButton22.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton22.IconRightCursor = System.Windows.Forms.Cursors.WaitCursor;
            this.bunifuButton22.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton22.IconSize = 25;
            this.bunifuButton22.IdleBorderColor = System.Drawing.Color.RoyalBlue;
            this.bunifuButton22.IdleBorderRadius = 30;
            this.bunifuButton22.IdleBorderThickness = 2;
            this.bunifuButton22.IdleFillColor = System.Drawing.Color.DarkCyan;
            this.bunifuButton22.IdleIconLeftImage = null;
            this.bunifuButton22.IdleIconRightImage = null;
            this.bunifuButton22.IndicateFocus = false;
            this.bunifuButton22.Location = new System.Drawing.Point(586, 328);
            this.bunifuButton22.Name = "bunifuButton22";
            this.bunifuButton22.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.OnDisabledState.BorderRadius = 30;
            this.bunifuButton22.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnDisabledState.BorderThickness = 2;
            this.bunifuButton22.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.OnDisabledState.IconLeftImage = null;
            this.bunifuButton22.OnDisabledState.IconRightImage = null;
            this.bunifuButton22.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton22.onHoverState.BorderRadius = 30;
            this.bunifuButton22.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.onHoverState.BorderThickness = 2;
            this.bunifuButton22.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton22.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.onHoverState.IconLeftImage = null;
            this.bunifuButton22.onHoverState.IconRightImage = null;
            this.bunifuButton22.OnIdleState.BorderColor = System.Drawing.Color.RoyalBlue;
            this.bunifuButton22.OnIdleState.BorderRadius = 30;
            this.bunifuButton22.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnIdleState.BorderThickness = 2;
            this.bunifuButton22.OnIdleState.FillColor = System.Drawing.Color.DarkCyan;
            this.bunifuButton22.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.OnIdleState.IconLeftImage = null;
            this.bunifuButton22.OnIdleState.IconRightImage = null;
            this.bunifuButton22.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton22.OnPressedState.BorderRadius = 30;
            this.bunifuButton22.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnPressedState.BorderThickness = 2;
            this.bunifuButton22.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton22.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.OnPressedState.IconLeftImage = null;
            this.bunifuButton22.OnPressedState.IconRightImage = null;
            this.bunifuButton22.Size = new System.Drawing.Size(182, 39);
            this.bunifuButton22.TabIndex = 82;
            this.bunifuButton22.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton22.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton22.TextMarginLeft = 0;
            this.bunifuButton22.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton22.UseDefaultRadiusAndThickness = true;
            this.bunifuButton22.UseWaitCursor = true;
            this.bunifuButton22.Click += new System.EventHandler(this.bunifuButton22_Click);
            // 
            // ModificarAutos
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1093, 455);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.txtIdSeguro);
            this.Controls.Add(this.bunifuLabel11);
            this.Controls.Add(this.txtKilometraje);
            this.Controls.Add(this.bunifuLabel10);
            this.Controls.Add(this.txtModelo);
            this.Controls.Add(this.bunifuLabel9);
            this.Controls.Add(this.txtClase);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.txtMatricula);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.txtMarca);
            this.Controls.Add(this.txtGrupo);
            this.Controls.Add(this.txtFechaCompra);
            this.Controls.Add(this.bunifuButton22);
            this.Controls.Add(this.bunifuButton21);
            this.Controls.Add(this.bunifuGradientPanel2);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Name = "ModificarAutos";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "ModificarAutos";
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel2;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox txtIdSeguro;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel11;
        private Bunifu.UI.WinForms.BunifuTextBox txtKilometraje;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel10;
        private Bunifu.UI.WinForms.BunifuTextBox txtModelo;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuTextBox txtClase;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuTextBox txtMatricula;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox txtMarca;
        private Bunifu.UI.WinForms.BunifuTextBox txtGrupo;
        private Bunifu.UI.WinForms.BunifuTextBox txtFechaCompra;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton22;
    }
}