
namespace Interfaz_proyecto_integrador
{
    partial class ModificarClienteIntermediario
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ModificarClienteIntermediario));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuGradientPanel2 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.crearAutoBoton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtDireccion = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNif = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtContactoPersona = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPoblacion = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtComision = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtCodigo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuGradientPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuGradientPanel2
            // 
            this.bunifuGradientPanel2.AccessibleRole = System.Windows.Forms.AccessibleRole.MenuBar;
            this.bunifuGradientPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel2.BackgroundImage")));
            this.bunifuGradientPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel2.BorderRadius = 1;
            this.bunifuGradientPanel2.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.bunifuGradientPanel2.GradientBottomLeft = System.Drawing.Color.SteelBlue;
            this.bunifuGradientPanel2.GradientBottomRight = System.Drawing.Color.RoyalBlue;
            this.bunifuGradientPanel2.GradientTopLeft = System.Drawing.Color.Teal;
            this.bunifuGradientPanel2.GradientTopRight = System.Drawing.Color.DarkCyan;
            this.bunifuGradientPanel2.Location = new System.Drawing.Point(0, 428);
            this.bunifuGradientPanel2.Name = "bunifuGradientPanel2";
            this.bunifuGradientPanel2.Quality = 10;
            this.bunifuGradientPanel2.Size = new System.Drawing.Size(1042, 54);
            this.bunifuGradientPanel2.TabIndex = 29;
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.DarkCyan;
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Atras";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.WaitCursor;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges1;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton21.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton21.ForeColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.WaitCursor;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.WaitCursor;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.RoyalBlue;
            this.bunifuButton21.IdleBorderRadius = 30;
            this.bunifuButton21.IdleBorderThickness = 2;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.DarkCyan;
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(329, 354);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 30;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 2;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.BorderRadius = 30;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 2;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.RoyalBlue;
            this.bunifuButton21.OnIdleState.BorderRadius = 30;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 2;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.DarkCyan;
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.BorderRadius = 30;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 2;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(182, 39);
            this.bunifuButton21.TabIndex = 27;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            this.bunifuButton21.UseWaitCursor = true;
            this.bunifuButton21.Click += new System.EventHandler(this.bunifuButton21_Click);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.AutoSize = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Britannic Bold", 24F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(297, 9);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(450, 42);
            this.bunifuLabel2.TabIndex = 2;
            this.bunifuLabel2.Text = "Modificar cliente intermediario";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.AccessibleRole = System.Windows.Forms.AccessibleRole.MenuBar;
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.SteelBlue;
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.RoyalBlue;
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.Teal;
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.DarkCyan;
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(1042, 54);
            this.bunifuGradientPanel1.TabIndex = 28;
            // 
            // crearAutoBoton
            // 
            this.crearAutoBoton.AllowAnimations = true;
            this.crearAutoBoton.AllowMouseEffects = true;
            this.crearAutoBoton.AllowToggling = false;
            this.crearAutoBoton.AnimationSpeed = 200;
            this.crearAutoBoton.AutoGenerateColors = false;
            this.crearAutoBoton.AutoRoundBorders = false;
            this.crearAutoBoton.AutoSizeLeftIcon = true;
            this.crearAutoBoton.AutoSizeRightIcon = true;
            this.crearAutoBoton.BackColor = System.Drawing.Color.Transparent;
            this.crearAutoBoton.BackColor1 = System.Drawing.Color.DarkCyan;
            this.crearAutoBoton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("crearAutoBoton.BackgroundImage")));
            this.crearAutoBoton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.crearAutoBoton.ButtonText = "Modificar";
            this.crearAutoBoton.ButtonTextMarginLeft = 0;
            this.crearAutoBoton.ColorContrastOnClick = 45;
            this.crearAutoBoton.ColorContrastOnHover = 45;
            this.crearAutoBoton.Cursor = System.Windows.Forms.Cursors.WaitCursor;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.crearAutoBoton.CustomizableEdges = borderEdges2;
            this.crearAutoBoton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.crearAutoBoton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.crearAutoBoton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.crearAutoBoton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.crearAutoBoton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.crearAutoBoton.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.crearAutoBoton.ForeColor = System.Drawing.Color.Transparent;
            this.crearAutoBoton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.crearAutoBoton.IconLeftCursor = System.Windows.Forms.Cursors.WaitCursor;
            this.crearAutoBoton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.crearAutoBoton.IconMarginLeft = 11;
            this.crearAutoBoton.IconPadding = 10;
            this.crearAutoBoton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.crearAutoBoton.IconRightCursor = System.Windows.Forms.Cursors.WaitCursor;
            this.crearAutoBoton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.crearAutoBoton.IconSize = 25;
            this.crearAutoBoton.IdleBorderColor = System.Drawing.Color.RoyalBlue;
            this.crearAutoBoton.IdleBorderRadius = 30;
            this.crearAutoBoton.IdleBorderThickness = 2;
            this.crearAutoBoton.IdleFillColor = System.Drawing.Color.DarkCyan;
            this.crearAutoBoton.IdleIconLeftImage = null;
            this.crearAutoBoton.IdleIconRightImage = null;
            this.crearAutoBoton.IndicateFocus = false;
            this.crearAutoBoton.Location = new System.Drawing.Point(551, 354);
            this.crearAutoBoton.Name = "crearAutoBoton";
            this.crearAutoBoton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.crearAutoBoton.OnDisabledState.BorderRadius = 30;
            this.crearAutoBoton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.crearAutoBoton.OnDisabledState.BorderThickness = 2;
            this.crearAutoBoton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.crearAutoBoton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.crearAutoBoton.OnDisabledState.IconLeftImage = null;
            this.crearAutoBoton.OnDisabledState.IconRightImage = null;
            this.crearAutoBoton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.crearAutoBoton.onHoverState.BorderRadius = 30;
            this.crearAutoBoton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.crearAutoBoton.onHoverState.BorderThickness = 2;
            this.crearAutoBoton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.crearAutoBoton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.crearAutoBoton.onHoverState.IconLeftImage = null;
            this.crearAutoBoton.onHoverState.IconRightImage = null;
            this.crearAutoBoton.OnIdleState.BorderColor = System.Drawing.Color.RoyalBlue;
            this.crearAutoBoton.OnIdleState.BorderRadius = 30;
            this.crearAutoBoton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.crearAutoBoton.OnIdleState.BorderThickness = 2;
            this.crearAutoBoton.OnIdleState.FillColor = System.Drawing.Color.DarkCyan;
            this.crearAutoBoton.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.crearAutoBoton.OnIdleState.IconLeftImage = null;
            this.crearAutoBoton.OnIdleState.IconRightImage = null;
            this.crearAutoBoton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.crearAutoBoton.OnPressedState.BorderRadius = 30;
            this.crearAutoBoton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.crearAutoBoton.OnPressedState.BorderThickness = 2;
            this.crearAutoBoton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.crearAutoBoton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.crearAutoBoton.OnPressedState.IconLeftImage = null;
            this.crearAutoBoton.OnPressedState.IconRightImage = null;
            this.crearAutoBoton.Size = new System.Drawing.Size(182, 39);
            this.crearAutoBoton.TabIndex = 31;
            this.crearAutoBoton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.crearAutoBoton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.crearAutoBoton.TextMarginLeft = 0;
            this.crearAutoBoton.TextPadding = new System.Windows.Forms.Padding(0);
            this.crearAutoBoton.UseDefaultRadiusAndThickness = true;
            this.crearAutoBoton.UseWaitCursor = true;
            this.crearAutoBoton.Click += new System.EventHandler(this.crearAutoBoton_Click);
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI", 14F);
            this.bunifuLabel7.Location = new System.Drawing.Point(477, 282);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(175, 25);
            this.bunifuLabel7.TabIndex = 64;
            this.bunifuLabel7.Text = "Contacto de persona";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.Location = new System.Drawing.Point(602, 226);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(36, 32);
            this.bunifuLabel6.TabIndex = 63;
            this.bunifuLabel6.Text = "NIF";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.Location = new System.Drawing.Point(66, 282);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(100, 32);
            this.bunifuLabel5.TabIndex = 62;
            this.bunifuLabel5.Text = "Comision";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.Location = new System.Drawing.Point(62, 226);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(104, 32);
            this.bunifuLabel4.TabIndex = 61;
            this.bunifuLabel4.Text = "Poblacion";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.Location = new System.Drawing.Point(538, 161);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(100, 32);
            this.bunifuLabel3.TabIndex = 60;
            this.bunifuLabel3.Text = "Direccion";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(78, 161);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(88, 32);
            this.bunifuLabel1.TabIndex = 59;
            this.bunifuLabel1.Text = "Nombre";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtDireccion
            // 
            this.txtDireccion.AcceptsReturn = false;
            this.txtDireccion.AcceptsTab = false;
            this.txtDireccion.AnimationSpeed = 200;
            this.txtDireccion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDireccion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDireccion.AutoSizeHeight = true;
            this.txtDireccion.BackColor = System.Drawing.Color.Transparent;
            this.txtDireccion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDireccion.BackgroundImage")));
            this.txtDireccion.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDireccion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDireccion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDireccion.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDireccion.BorderRadius = 1;
            this.txtDireccion.BorderThickness = 1;
            this.txtDireccion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDireccion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccion.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDireccion.DefaultText = "";
            this.txtDireccion.FillColor = System.Drawing.Color.White;
            this.txtDireccion.HideSelection = true;
            this.txtDireccion.IconLeft = null;
            this.txtDireccion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccion.IconPadding = 10;
            this.txtDireccion.IconRight = null;
            this.txtDireccion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccion.Lines = new string[0];
            this.txtDireccion.Location = new System.Drawing.Point(658, 154);
            this.txtDireccion.MaxLength = 32767;
            this.txtDireccion.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDireccion.Modified = false;
            this.txtDireccion.Multiline = false;
            this.txtDireccion.Name = "txtDireccion";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccion.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDireccion.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccion.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccion.OnIdleState = stateProperties4;
            this.txtDireccion.Padding = new System.Windows.Forms.Padding(3);
            this.txtDireccion.PasswordChar = '\0';
            this.txtDireccion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDireccion.PlaceholderText = "CAMPO";
            this.txtDireccion.ReadOnly = false;
            this.txtDireccion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDireccion.SelectedText = "";
            this.txtDireccion.SelectionLength = 0;
            this.txtDireccion.SelectionStart = 0;
            this.txtDireccion.ShortcutsEnabled = true;
            this.txtDireccion.Size = new System.Drawing.Size(292, 39);
            this.txtDireccion.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDireccion.TabIndex = 57;
            this.txtDireccion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDireccion.TextMarginBottom = 0;
            this.txtDireccion.TextMarginLeft = 3;
            this.txtDireccion.TextMarginTop = 1;
            this.txtDireccion.TextPlaceholder = "CAMPO";
            this.txtDireccion.UseSystemPasswordChar = false;
            this.txtDireccion.WordWrap = true;
            // 
            // txtNif
            // 
            this.txtNif.AcceptsReturn = false;
            this.txtNif.AcceptsTab = false;
            this.txtNif.AnimationSpeed = 200;
            this.txtNif.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNif.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNif.AutoSizeHeight = true;
            this.txtNif.BackColor = System.Drawing.Color.Transparent;
            this.txtNif.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNif.BackgroundImage")));
            this.txtNif.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNif.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNif.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNif.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNif.BorderRadius = 1;
            this.txtNif.BorderThickness = 1;
            this.txtNif.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNif.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNif.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNif.DefaultText = "";
            this.txtNif.FillColor = System.Drawing.Color.White;
            this.txtNif.HideSelection = true;
            this.txtNif.IconLeft = null;
            this.txtNif.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNif.IconPadding = 10;
            this.txtNif.IconRight = null;
            this.txtNif.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNif.Lines = new string[0];
            this.txtNif.Location = new System.Drawing.Point(658, 219);
            this.txtNif.MaxLength = 32767;
            this.txtNif.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNif.Modified = false;
            this.txtNif.Multiline = false;
            this.txtNif.Name = "txtNif";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNif.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNif.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNif.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNif.OnIdleState = stateProperties8;
            this.txtNif.Padding = new System.Windows.Forms.Padding(3);
            this.txtNif.PasswordChar = '\0';
            this.txtNif.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNif.PlaceholderText = "CAMPO";
            this.txtNif.ReadOnly = false;
            this.txtNif.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNif.SelectedText = "";
            this.txtNif.SelectionLength = 0;
            this.txtNif.SelectionStart = 0;
            this.txtNif.ShortcutsEnabled = true;
            this.txtNif.Size = new System.Drawing.Size(292, 39);
            this.txtNif.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNif.TabIndex = 56;
            this.txtNif.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNif.TextMarginBottom = 0;
            this.txtNif.TextMarginLeft = 3;
            this.txtNif.TextMarginTop = 1;
            this.txtNif.TextPlaceholder = "CAMPO";
            this.txtNif.UseSystemPasswordChar = false;
            this.txtNif.WordWrap = true;
            // 
            // txtContactoPersona
            // 
            this.txtContactoPersona.AcceptsReturn = false;
            this.txtContactoPersona.AcceptsTab = false;
            this.txtContactoPersona.AnimationSpeed = 200;
            this.txtContactoPersona.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtContactoPersona.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtContactoPersona.AutoSizeHeight = true;
            this.txtContactoPersona.BackColor = System.Drawing.Color.Transparent;
            this.txtContactoPersona.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtContactoPersona.BackgroundImage")));
            this.txtContactoPersona.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtContactoPersona.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtContactoPersona.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtContactoPersona.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtContactoPersona.BorderRadius = 1;
            this.txtContactoPersona.BorderThickness = 1;
            this.txtContactoPersona.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtContactoPersona.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContactoPersona.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtContactoPersona.DefaultText = "";
            this.txtContactoPersona.FillColor = System.Drawing.Color.White;
            this.txtContactoPersona.HideSelection = true;
            this.txtContactoPersona.IconLeft = null;
            this.txtContactoPersona.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContactoPersona.IconPadding = 10;
            this.txtContactoPersona.IconRight = null;
            this.txtContactoPersona.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContactoPersona.Lines = new string[0];
            this.txtContactoPersona.Location = new System.Drawing.Point(658, 275);
            this.txtContactoPersona.MaxLength = 32767;
            this.txtContactoPersona.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtContactoPersona.Modified = false;
            this.txtContactoPersona.Multiline = false;
            this.txtContactoPersona.Name = "txtContactoPersona";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtContactoPersona.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtContactoPersona.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtContactoPersona.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtContactoPersona.OnIdleState = stateProperties12;
            this.txtContactoPersona.Padding = new System.Windows.Forms.Padding(3);
            this.txtContactoPersona.PasswordChar = '\0';
            this.txtContactoPersona.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtContactoPersona.PlaceholderText = "CAMPO";
            this.txtContactoPersona.ReadOnly = false;
            this.txtContactoPersona.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtContactoPersona.SelectedText = "";
            this.txtContactoPersona.SelectionLength = 0;
            this.txtContactoPersona.SelectionStart = 0;
            this.txtContactoPersona.ShortcutsEnabled = true;
            this.txtContactoPersona.Size = new System.Drawing.Size(292, 39);
            this.txtContactoPersona.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtContactoPersona.TabIndex = 55;
            this.txtContactoPersona.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtContactoPersona.TextMarginBottom = 0;
            this.txtContactoPersona.TextMarginLeft = 3;
            this.txtContactoPersona.TextMarginTop = 1;
            this.txtContactoPersona.TextPlaceholder = "CAMPO";
            this.txtContactoPersona.UseSystemPasswordChar = false;
            this.txtContactoPersona.WordWrap = true;
            // 
            // txtPoblacion
            // 
            this.txtPoblacion.AcceptsReturn = false;
            this.txtPoblacion.AcceptsTab = false;
            this.txtPoblacion.AnimationSpeed = 200;
            this.txtPoblacion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPoblacion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPoblacion.AutoSizeHeight = true;
            this.txtPoblacion.BackColor = System.Drawing.Color.Transparent;
            this.txtPoblacion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPoblacion.BackgroundImage")));
            this.txtPoblacion.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPoblacion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPoblacion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPoblacion.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPoblacion.BorderRadius = 1;
            this.txtPoblacion.BorderThickness = 1;
            this.txtPoblacion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPoblacion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPoblacion.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPoblacion.DefaultText = "";
            this.txtPoblacion.FillColor = System.Drawing.Color.White;
            this.txtPoblacion.HideSelection = true;
            this.txtPoblacion.IconLeft = null;
            this.txtPoblacion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPoblacion.IconPadding = 10;
            this.txtPoblacion.IconRight = null;
            this.txtPoblacion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPoblacion.Lines = new string[0];
            this.txtPoblacion.Location = new System.Drawing.Point(172, 219);
            this.txtPoblacion.MaxLength = 32767;
            this.txtPoblacion.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPoblacion.Modified = false;
            this.txtPoblacion.Multiline = false;
            this.txtPoblacion.Name = "txtPoblacion";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPoblacion.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPoblacion.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPoblacion.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPoblacion.OnIdleState = stateProperties16;
            this.txtPoblacion.Padding = new System.Windows.Forms.Padding(3);
            this.txtPoblacion.PasswordChar = '\0';
            this.txtPoblacion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPoblacion.PlaceholderText = "CAMPO";
            this.txtPoblacion.ReadOnly = false;
            this.txtPoblacion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPoblacion.SelectedText = "";
            this.txtPoblacion.SelectionLength = 0;
            this.txtPoblacion.SelectionStart = 0;
            this.txtPoblacion.ShortcutsEnabled = true;
            this.txtPoblacion.Size = new System.Drawing.Size(292, 39);
            this.txtPoblacion.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPoblacion.TabIndex = 54;
            this.txtPoblacion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPoblacion.TextMarginBottom = 0;
            this.txtPoblacion.TextMarginLeft = 3;
            this.txtPoblacion.TextMarginTop = 1;
            this.txtPoblacion.TextPlaceholder = "CAMPO";
            this.txtPoblacion.UseSystemPasswordChar = false;
            this.txtPoblacion.WordWrap = true;
            // 
            // txtComision
            // 
            this.txtComision.AcceptsReturn = false;
            this.txtComision.AcceptsTab = false;
            this.txtComision.AnimationSpeed = 200;
            this.txtComision.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtComision.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtComision.AutoSizeHeight = true;
            this.txtComision.BackColor = System.Drawing.Color.Transparent;
            this.txtComision.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtComision.BackgroundImage")));
            this.txtComision.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtComision.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtComision.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtComision.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtComision.BorderRadius = 1;
            this.txtComision.BorderThickness = 1;
            this.txtComision.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtComision.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtComision.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtComision.DefaultText = "";
            this.txtComision.FillColor = System.Drawing.Color.White;
            this.txtComision.HideSelection = true;
            this.txtComision.IconLeft = null;
            this.txtComision.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtComision.IconPadding = 10;
            this.txtComision.IconRight = null;
            this.txtComision.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtComision.Lines = new string[0];
            this.txtComision.Location = new System.Drawing.Point(172, 275);
            this.txtComision.MaxLength = 32767;
            this.txtComision.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtComision.Modified = false;
            this.txtComision.Multiline = false;
            this.txtComision.Name = "txtComision";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtComision.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtComision.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtComision.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtComision.OnIdleState = stateProperties20;
            this.txtComision.Padding = new System.Windows.Forms.Padding(3);
            this.txtComision.PasswordChar = '\0';
            this.txtComision.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtComision.PlaceholderText = "CAMPO";
            this.txtComision.ReadOnly = false;
            this.txtComision.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtComision.SelectedText = "";
            this.txtComision.SelectionLength = 0;
            this.txtComision.SelectionStart = 0;
            this.txtComision.ShortcutsEnabled = true;
            this.txtComision.Size = new System.Drawing.Size(292, 39);
            this.txtComision.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtComision.TabIndex = 53;
            this.txtComision.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtComision.TextMarginBottom = 0;
            this.txtComision.TextMarginLeft = 3;
            this.txtComision.TextMarginTop = 1;
            this.txtComision.TextPlaceholder = "CAMPO";
            this.txtComision.UseSystemPasswordChar = false;
            this.txtComision.WordWrap = true;
            // 
            // txtNombre
            // 
            this.txtNombre.AcceptsReturn = false;
            this.txtNombre.AcceptsTab = false;
            this.txtNombre.AnimationSpeed = 200;
            this.txtNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNombre.AutoSizeHeight = true;
            this.txtNombre.BackColor = System.Drawing.Color.Transparent;
            this.txtNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNombre.BackgroundImage")));
            this.txtNombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNombre.BorderRadius = 1;
            this.txtNombre.BorderThickness = 1;
            this.txtNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNombre.DefaultText = "";
            this.txtNombre.FillColor = System.Drawing.Color.White;
            this.txtNombre.HideSelection = true;
            this.txtNombre.IconLeft = null;
            this.txtNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.IconPadding = 10;
            this.txtNombre.IconRight = null;
            this.txtNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombre.Lines = new string[0];
            this.txtNombre.Location = new System.Drawing.Point(172, 154);
            this.txtNombre.MaxLength = 32767;
            this.txtNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNombre.Modified = false;
            this.txtNombre.Multiline = false;
            this.txtNombre.Name = "txtNombre";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNombre.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombre.OnIdleState = stateProperties24;
            this.txtNombre.Padding = new System.Windows.Forms.Padding(3);
            this.txtNombre.PasswordChar = '\0';
            this.txtNombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNombre.PlaceholderText = "CAMPO";
            this.txtNombre.ReadOnly = false;
            this.txtNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNombre.SelectedText = "";
            this.txtNombre.SelectionLength = 0;
            this.txtNombre.SelectionStart = 0;
            this.txtNombre.ShortcutsEnabled = true;
            this.txtNombre.Size = new System.Drawing.Size(292, 39);
            this.txtNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNombre.TabIndex = 52;
            this.txtNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNombre.TextMarginBottom = 0;
            this.txtNombre.TextMarginLeft = 3;
            this.txtNombre.TextMarginTop = 1;
            this.txtNombre.TextPlaceholder = "CAMPO";
            this.txtNombre.UseSystemPasswordChar = false;
            this.txtNombre.WordWrap = true;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel8.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel8.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel8.Location = new System.Drawing.Point(340, 84);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(77, 32);
            this.bunifuLabel8.TabIndex = 66;
            this.bunifuLabel8.Text = "Codigo";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtCodigo
            // 
            this.txtCodigo.AcceptsReturn = false;
            this.txtCodigo.AcceptsTab = false;
            this.txtCodigo.AnimationSpeed = 200;
            this.txtCodigo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCodigo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCodigo.AutoSizeHeight = true;
            this.txtCodigo.BackColor = System.Drawing.Color.Transparent;
            this.txtCodigo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCodigo.BackgroundImage")));
            this.txtCodigo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCodigo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCodigo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCodigo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCodigo.BorderRadius = 1;
            this.txtCodigo.BorderThickness = 1;
            this.txtCodigo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCodigo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodigo.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCodigo.DefaultText = "";
            this.txtCodigo.FillColor = System.Drawing.Color.White;
            this.txtCodigo.HideSelection = true;
            this.txtCodigo.IconLeft = null;
            this.txtCodigo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodigo.IconPadding = 10;
            this.txtCodigo.IconRight = null;
            this.txtCodigo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodigo.Lines = new string[0];
            this.txtCodigo.Location = new System.Drawing.Point(434, 77);
            this.txtCodigo.MaxLength = 32767;
            this.txtCodigo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCodigo.Modified = false;
            this.txtCodigo.Multiline = false;
            this.txtCodigo.Name = "txtCodigo";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodigo.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCodigo.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodigo.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodigo.OnIdleState = stateProperties28;
            this.txtCodigo.Padding = new System.Windows.Forms.Padding(3);
            this.txtCodigo.PasswordChar = '\0';
            this.txtCodigo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCodigo.PlaceholderText = "CAMPO";
            this.txtCodigo.ReadOnly = false;
            this.txtCodigo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCodigo.SelectedText = "";
            this.txtCodigo.SelectionLength = 0;
            this.txtCodigo.SelectionStart = 0;
            this.txtCodigo.ShortcutsEnabled = true;
            this.txtCodigo.Size = new System.Drawing.Size(292, 39);
            this.txtCodigo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCodigo.TabIndex = 65;
            this.txtCodigo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCodigo.TextMarginBottom = 0;
            this.txtCodigo.TextMarginLeft = 3;
            this.txtCodigo.TextMarginTop = 1;
            this.txtCodigo.TextPlaceholder = "CAMPO";
            this.txtCodigo.UseSystemPasswordChar = false;
            this.txtCodigo.WordWrap = true;
            // 
            // ModificarClienteIntermediario
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1042, 482);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.txtCodigo);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.txtDireccion);
            this.Controls.Add(this.txtNif);
            this.Controls.Add(this.txtContactoPersona);
            this.Controls.Add(this.txtPoblacion);
            this.Controls.Add(this.txtComision);
            this.Controls.Add(this.txtNombre);
            this.Controls.Add(this.crearAutoBoton);
            this.Controls.Add(this.bunifuGradientPanel2);
            this.Controls.Add(this.bunifuButton21);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Name = "ModificarClienteIntermediario";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "ModificarClienteIntermediario";
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 crearAutoBoton;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox txtDireccion;
        private Bunifu.UI.WinForms.BunifuTextBox txtNif;
        private Bunifu.UI.WinForms.BunifuTextBox txtContactoPersona;
        private Bunifu.UI.WinForms.BunifuTextBox txtPoblacion;
        private Bunifu.UI.WinForms.BunifuTextBox txtComision;
        private Bunifu.UI.WinForms.BunifuTextBox txtNombre;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuTextBox txtCodigo;
    }
}